### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [bartok765/galaxy_blizzard_plugin#1]
Hi.

We would like to fork your repo and keep track based on the work being done here, if you agree. 

This is because we have no time to keep developing the integration on our side and you've solved some build issues itself. It's also beneficial that your repo is not a fork, as we can sync it using our fork-updater like for example https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar

The syncing code can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater
I see that you already added manifest.json to `src` so it should work out of the box (I hope).

**Comment by bartok765** [comment]
Oh, I see. Does it mean that I have to maintain all the stuff currently kept in your repo? I can't promise I will be able to fix current issues, but if that helps I can try. Or at least accept PRs from time to time. Is it enough? And what will happen with https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet?

**Comment by FriendsOfGalaxy** [comment]
> Or at least accept PRs from time to time. Is it enough?
yes, it's perfectly fine. We will review the code while syncing on any change from `fog-release` branch

Also - please do not change guid - will be easier to switch for current plugin users.

**Comment by bartok765** [comment]
Ok, guid reversed
