### ISSUE TITLE
Need _psutil_windows.cp37-win32.pyd file to make the plugin work right.

### ISSUE THREAD

**Issue by a358003542** [bartok765/galaxy_blizzard_plugin#12]
I have tested on my machine , sure about the fact that need additional _psutil_windows.cp37-win32.pyd file to make the plugin work right. 

```
Galaxy version : 2.0.13Beta 32bits
OS version win10 home edition V18363.719 64 bits 
plugin version: 1.0.2
python version: 3.7 64bits
```
Personal guess this problem only occurred on windows, and it is not the plugin itself problem, But if whose user install the plugin from source and his python version is 64 bits would cause this issue.

**Comment by saitho** [comment]
Can't confirm that issue. I am running a 64bit Windows 10 but using a 32bit Python, so I might now run into this issue. ;) But I guess that change makes sense?

**Comment by bartok765** [comment]
@a358003542 can you retest now?

**Comment by a358003542** [comment]
@bartok765 Yes, the #13 has fixed this problem, this issue should be  closed now.
