### ISSUE TITLE
China diablo3 fails to install

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [bartok765/galaxy_blizzard_plugin#15]
**Describe the bug**
Regarding to 1.1.0 update, almost everything work fine but I found an issue with diablo3.
Probably because of unknown id for `d3cn`. Someone from China that have d3cn has to check result of his `backend_client.get_owned_games()` to find this unknown id.

**To Reproduce**
1. Log in with china account that have no diablo3 installed on local computer
2. Click Install
3. See this in battlenet
<img width="397" alt="Screenshot 2020-03-20 at 11 52 41" src="https://user-images.githubusercontent.com/48480506/77178418-54aecf00-6ac7-11ea-9423-0fe6fd4c14db.png">

**Logs**

```
2020-03-20 20:47:37,635 - root - INFO - Adding ? 暗黑破壞神III to installed games
2020-03-20 20:47:37,641 - root - DEBUG - Detected installation begin
2020-03-20 20:47:37,641 - root - INFO - Changing game ? state to LocalGameState.None_
2020-03-20 20:47:37,641 - galaxy.api.jsonrpc - INFO - Sending notification: method=local_game_status_changed, params={'local_game': LocalGame(game_id='?', local_game_state=<LocalGameState.None_: 0>)}
2020-03-20 20:47:37,641 - galaxy.api.jsonrpc - DEBUG - Sending 125 bytes of data
```

**Comment by bartok765** [comment]
@a358003542 can you help? :)

**Comment by a358003542** [comment]
@bartok765  That is because of d3cn has a unknown blizzard_id : 

```
        BlizzardGame('d3cn', '暗黑破壞神III', '?', 'D3CN', False),
        BlizzardGame('diablo3', 'Diablo III', '17459', 'D3', True),
```
 I know d3cn blizzard id is also same as diablo3 to 17459,  so it is conflict with the diablo3 , How to handle this problem need more discuss.

**Comment by bartok765** [comment]
Do you mean it conflics technically when accessing Blizzard instance? Then key access `Blizzard[id] ` cannot rely on this kind of id

**Comment by a358003542** [comment]
@bartok765 the program need to found the uid based on the id which in the install case is the blizzard_id of 17459. but there have two 17459 id, seems like there need a region judgement.

**Comment by bartok765** [comment]
Ah, your right. But at this point we authentication should be already performed, so we don't need guess for region - returned cookies knows true. We can store this in persistent cache maybe

**Comment by a358003542** [comment]
@bartok765 good advice. make fix this issue simpler.  please review the pull requrests #19 .
