### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by lackovic** [bartok765/galaxy_blizzard_plugin#16]
Can you add to the README the instructions on how uninstall this plugin?

**Comment by bartok765** [comment]
yes, please. I suppose you wanted to remove all the data from Galaxy not only to stop local process.

I you want to keep games as owned, but do not wish to see running plugin process, kill the process manually and then remove plugin local database at 
`C:\ProgramData\GOG.com\Galaxy\storage\plugins`

**Comment by lackovic** [comment]
Is this the same plugin that can be installed through Galaxy user interface?

![2020-03-24_084818](https://user-images.githubusercontent.com/1663053/77396595-b9f70e80-6dac-11ea-93d7-855cc23f342d.png)

If yes, it may be useful to mention that in the README too.

**Comment by bartok765** [comment]
No exactly. I've updated README.md to explain. Also see #1
