### ISSUE TITLE
Destiny 2 can't be installed

### ISSUE THREAD

**Issue by yoshimo** [bartok765/galaxy_blizzard_plugin#29]
**Describe the bug**
GoG shows Destiny2 being available from both Steam and Bnet.
If you hit install in the gog section, bnet starts up and complains about not being able to install the game at this moment. I doubt the reccomended bnet launcher update will fix this anytime soon as it isn't even shown as a partner game.

Not offer the game for installation at all.

**Comment by bartok765** [comment]
Hmm, can you login into https://www.blizzard.com/ and then go to
https://account.blizzard.com/api/games-and-subs
and tell me which games you see there with which `title_id`? 

Looks contrary to #24 

Nevertheless I think we can remove Destiny2 definition from plugin

**Comment by yoshimo** [comment]
we have

        "titleId": 1146311730,
        "localizedGameName": "Destiny 2",

        "titleId": 22323,
        "localizedGameName": "Warcraft III: Reforged",

        "titleId": 21297,
        "localizedGameName": "StarCraft® Remastered",

        "titleId": 21298,
        "localizedGameName": "StarCraft® II: Heart of the Swarm®",

        "titleId": 5272175,
        "localizedGameName": "Overwatch®",

        "titleId": 1214607983,
        "localizedGameName": "Heroes of the Storm®",

        "titleId": 1465140039,
        "localizedGameName": "Hearthstone®",

        "titleId": 17459,
        "localizedGameName": "Diablo® III: Reaper of Souls™",

        "titleId": 5730135,
        "localizedGameName": "World of Warcraft®: Legion",
(WoW is there multiple times with different localized names though, depending on the expansion and gameAccountId/gameAccountName)


Maybe we can filter it out just if there is no account connected to it to keep people that played destiny over bnet before it was removed happy?

`{
        "titleId": 1146311730,
        "localizedGameName": "Destiny 2",
        "gameAccountName": null,
        "gameAccountUniqueId": null,
        "gameAccountRegion": null,
        "regionalGameFranchiseIconFilename": "destiny-2.svg",
        "gameAccountStatus": null,
        "lastPlayedDateMillis": null,
        "titleHasSubscriptions": false,
        "titleHasGameTime": false,
        "accountSubscriptionView": null,
        "gameTimeView": null,
        "displayOrder": 1000
    }`

**Comment by bartok765** [comment]
@yoshimo 
> Maybe we can filter it out just if there is no account connected to it to keep people that played destiny over bnet before it was removed happy?

hmm, good point. But I'm not sure if `lastPlayedDateMillis` or `gameTimeView` works at all. I have `null` in all my games. Have you played Destiny or have not `null` for any game there?
