### ISSUE TITLE
Modern Warfare 2 Campaign Remastered not showing up.

### ISSUE THREAD

**Issue by EASK8ER52** [bartok765/galaxy_blizzard_plugin#38]
Basically this plugin works mostly fine. I got it straight from GOG. Only issue is that Modern Warfare 2 Campaign Remastered doesn't show up in the library. Is there any way to fix this? Is there something that needs to be done that I'm not doing?

**Comment by bartok765** [comment]
Hey @EASK8ER52 see this issue #24 
I had no much time recently. PR welcomed. I'm closing this issue as duplicate
