### ISSUE TITLE
Games that requires Update shown as not installed

### ISSUE THREAD

**Issue by georgehank** [bartok765/galaxy_blizzard_plugin#40]
None of my installed games are shown as installed.

Expected: Duh, of course I'd like my installed games with a "Play" button instead of an "Install" button.

Suspicion: all the games need updates (stupid razznfrazzn Battle.net not updating games if you haven't played them "recently" (whatever that actually means, but I digress)).

Suspicion confirmed: after updating, "Install" changes to "Play".  So, _sigh_, it's actually a bug in Galaxy 2.0, since GOG games always update automatically (if not changed from default setting).  I guess.

**Comment by derrickb** [comment]
Experiencing this as well.

**Comment by bartok765** [comment]
that is a bug in the the plugin. I'll fix it when have a time. PR welcomed.
