### ISSUE TITLE
Crash Bandicoot 4 not detected

### ISSUE THREAD

**Issue by nwarrenfl** [bartok765/galaxy_blizzard_plugin#55]
Crash Bandicoot 4: It's About Time doesn't get imported in GOG Galaxy.

EDIT:
Made a pull request:
https://github.com/bartok765/galaxy_blizzard_plugin/pull/56

After some searching, I found following JSON object about the game when going to my account:
{
  "titleId": 1464615513,
  "localizedGameName": "Crash Bandicoot™ 4: It’s About Time",
  "gameAccountName": null,
  "gameAccountUniqueId": {
    "gameAccountId": 952609785,
    "gameServiceRegionId": 2,
    "programId": 1464615513
  },
  "gameAccountRegion": "EU",
  "regionalGameFranchiseIconFilename": "crash-bandicoot-4.svg",
  "gameAccountStatus": "Good",
  "lastPlayedDateMillis": null,
  "titleHasSubscriptions": false,
  "titleHasGameTime": false,
  "accountSubscriptionView": null,
  "gameTimeView": null,
  "displayOrder": 2000,
  "customDownloadLink": null
}

Anyways, hope this helps :)

**Comment by bartok765** [comment]
Closed by #56
