### ISSUE TITLE
Plugin losing authentication

### ISSUE THREAD

**Issue by BradB111** [bartok765/galaxy_blizzard_plugin#67]
**Describe the bug**
Plugin often loses authentication causing a login approx. once per 24 hours

**To Reproduce**
Wait 1-2 days

**Expected behaviour**
For the plugin to not lose authentication.

**Attached logs**
Let me know if any are required and which ones required if so.

**Comment by bartok765** [comment]
Hi @BradB111,

I have no repro, please attach battlenet logs from C:\ProgramData\GOG.com\Galaxy\logs
Those with extension `log` and `log.0`

**Comment by BradB111** [comment]
This seems to have been resolved after manually deleting the plugin and redownloading via the GOG Galaxy client
