### ISSUE TITLE
Call of Duty Vanguard

### ISSUE THREAD

**Issue by Curotos** [bartok765/galaxy_blizzard_plugin#68]
Vanguard has not been added to GOG yet but I saw last year for cold war there is a way to manually enter a code into the Definitions.py file and was wondering what the format would be to add vanguard

**Comment by Kinematic9** [comment]
I think it was mentioned here: https://github.com/bartok765/galaxy_blizzard_plugin/issues/42

I also don't see it yet on my end, assuming they will push it out soon.

**Comment by BradB111** [comment]
I managed to add this with the following: 

![image](https://user-images.githubusercontent.com/17122433/140644038-83459c76-ab8f-480e-a002-c9cf42d7bace.png)

I will try and make a PR

**Comment by Curotos** [comment]
I added the two vanguard lines as well as the commas on the line beforehand, is there anything else I would be missing because it still does not show up?

**Comment by BradB111** [comment]
> I added the two vanguard lines as well as the commas on the line beforehand, is there anything else I would be missing because it still does not show up?

Make sure the lines are exact, you have added commas to the lines above and that you have disconnected the plug-in in the settings and then reconnect.
